### ISSUE TITLE
It works

### ISSUE THREAD

**Issue by blat-blatnik** [IndoorAdventurer/CG_Competition#1]
Nice submission guys. I was impressed that you did not bake the reflections into a texture like you did with the lighting, you actually calculate the reflections in real time by rendering the scene multiple times.

Although you really weren't kidding about the compile taking long. My pc crashed trying to do it hahaha. But it worked on the second try.

Thanks for participating and I hope you had fun making the scene :)

Here's a screenshot of it running on my machine.

- Boris

![Screenshot](https://user-images.githubusercontent.com/55242398/113490687-f84d0080-94cb-11eb-8839-40a9d7cfc4cb.jpeg)

**Comment by IndoorAdventurer** [comment]
Nice! Yeah it also crashed for twice when I compiled on my Laptop. I saw QT literally creates a C++ source file with an array of characters containing the binary information.. so no wonder it takes that long :-)

I'm happy you enjoyed it ^^

Kind regards
